apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-project
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-capstone-project-app
  template:
    metadata:
      name: devops-capstone-project-pod
      labels:
        app: devops-capstone-project-app
    spec:
      containers:
      - name: devops-capstone-project-container
        image: mtammam/capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: devops-capstone-project-svc
  labels:
    app: devops-capstone-project-app
spec:
  selector:
    app: devops-capstone-project-app
  type: LoadBalancer
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80